import { StructurePlaylist } from '@models/playlist.model';

export const listOfMusic: StructurePlaylist[] = [
  {
    id: 1,
    name: 'Canciones de Morat',
    description: 'todas las canciones de morat',
    presentacionImage: 'https://i.scdn.co/image/ab67616d0000b2730c929d54495f38b910f48643',
    songs: [
      {
        id: 1,
        description: 'morat acuerdate de mi ',
        name: 'Acuérdate de mí',
        image: '',
        urlsong: '/assets/audio/Morat - Acuérdate De Mí (Live) _ Vevo X(MP3_70K).mp3',
      },
      {
        id: 2,
        description: 'Al aire de morat',
        name: 'Al aire',
        image: '',
        urlsong: '/assets/audio/Morat - Al Aire(MP3_70K).mp3',
      },
      {
        id: 3,
        description: 'Amor con hielo de morat',
        name: 'Amor Con hielo',
        image: '',
        urlsong: '/assets/audio/Morat - Amor Con Hielo(MP3_70K).mp3',
      },
      {
        id: 4,
        description: 'Antes de los veinte de morat',
        name: 'Antes de los veinte',
        image: '',
        urlsong: '/assets/audio/Morat - Antes De Los Veinte (Visualiser)(MP3_70K).mp3',
      },
      {
        id: 5,
        description: 'Cuando nadie los ve morat',
        name: 'Cuando Nadie ve',
        image: '',
        urlsong: '/assets/audio/Morat - Cuando Nadie Ve(MP3_70K).mp3',
      },
      {
        id: 6,
        description: 'Cuanto me duele de morat',
        name: 'Cuánto me duele',
        image: '',
        urlsong: '/assets/audio/Morat - Cuánto Me Duele(MP3_70K).mp3',
      },
      {
        id: 7,
        description: 'En un solo dia de morat',
        name: 'En un sólo Día',
        image: '',
        urlsong: '/assets/audio/Morat - En Un Sólo Día(MP3_70K).mp3',
      },
      {
        id: 8,
        description: 'Eres tú de morat',
        name: 'Eres tú',
        image: '',
        urlsong: '/assets/audio/Morat - Eres Tú (Official Audio)(MP3_70K).mp3',
      },
      {
        id: 9,
        description: 'Huele a gol de morat',
        name: 'Huele a gol',
        image: '',
        urlsong: '/assets/audio/Morat - Huele a Gol(MP3_70K).mp3',
      },
      {
        id: 10,
        description: 'Mi nuevo vicio de morat',
        name: 'Mi nuevo Vicio',
        image: '',
        urlsong: '/assets/audio/Morat - Mi Nuevo Vicio (Lyric)(MP3_70K).mp3',
      },
      {
        id: 12,
        description: 'mi vida entera de morat',
        name: 'Mi vida entera',
        image: '',
        urlsong: '/assets/audio/Morat - Mi Vida Entera (Live) _ Vevo X(MP3_70K).mp3',
      },
      {
        id: 13,
        description: 'No hay mas que hablar de morat',
        name: 'No hay Más que hablar',
        image: '',
        urlsong: '/assets/audio/Morat - No Hay Más Que Hablar(MP3_70K).mp3',
      },
      {
        id: 14,
        description: 'Nunca te olvide de morat',
        name: 'Nunca te Olvidé',
        image: '',
        urlsong: '/assets/audio/Morat - Nunca Te Olvidé(MP3_70K).mp3',
      },
      {
        id: 15,
        description: 'yo mas te adoro de morat',
        name: 'Yo más te adoro',
        image: '',
        urlsong: '/assets/audio/Morat - Yo Más Te Adoro(MP3_70K).mp3',
      },
      {
        id: 16,
        description: 'Mi pesadilla morat - cepeda',
        name: 'Mi pesadilla',
        image: '',
        urlsong: '/assets/audio/Morat_ Andrés Cepeda - Mi Pesadilla(MP3_70K).mp3',
      },
      {
        id: 17,
        description: 'simplemente pasan de morat',
        name: 'Simplemente Pasan',
        image: '',
        urlsong: '/assets/audio/Morat_ Cami - Simplemente Pasan(MP3_70K).mp3',
      },
    ],
  },
];
